feat: add thumbnail images

diff --git a/homedir/.local/bin/yt-transcript b/homedir/.local/bin/yt-transcript
--- a/homedir/.local/bin/yt-transcript
+++ b/homedir/.local/bin/yt-transcript
@@ -4,12 +4,9 @@ set -euo pipefail
 # given a youtube URL, download the video, transcribe it, and create a
 # decent-looking HTML transcript to read
 
-# TODO: add key images to the transcript. Or maybe screencap every 30s? How to
-# intersperse them sensibly.
-
 function usage() {
         cat <<"EOF"
-Usage: ,yt-transcript <youtube-url>
+Usage: yt-transcript <youtube-url>
 
 Output a transcript of the given youtube video.
 
@@ -32,6 +29,8 @@ fi
 # default to suppressing ffmpeg and ytdlp output
 ffmpegquiet=(-hide_banner -loglevel error)
 ytdlpquiet=(--quiet)
+thumbs=
+thumbinterval=30 # default 30s between thumbs
 
 # parse command line arguments
 while true; do
@@ -41,6 +40,15 @@ while true; do
             ffmpegquiet=()
             ytdlpquiet=()
             shift
+        ;;
+        -thumbs)
+            thumbs=yup
+            shift
+        ;;
+        -thumbinterval)
+            thumbinterval=$2
+            shift 2
+            break
         ;;
         *)
             break
@@ -75,7 +83,7 @@ if [ ! -d $yttranscript_cache_folder ]; then
     mkdir $yttranscript_cache_folder
 fi
 
-# 1. download audio of talk if we haven't yet
+# download audio of talk if we haven't yet
 ytdl_audio_outfile="$yttranscript_cache_folder/rawaudio_$yturl_clean.%(ext)s"
 rawaudio=$(find "$yttranscript_cache_folder" -name "rawaudio_$yturl_clean*")
 if [ -z "$rawaudio" ]; then
@@ -87,49 +95,42 @@ if [ -z "$rawaudio" ]; then
         exit 1
     fi
 fi
-
 # re-run the `find` bc the file should exist now if it didn't before
 rawaudio=$(find "$yttranscript_cache_folder" -name "rawaudio_$yturl_clean*")
 
-# 2. convert into 16-bit wav file if we haven't yet
-wav_transcript="$yttranscript_cache_folder/audio_$yturl_clean.wav"
-if [ ! -f "$wav_transcript" ]; then
+
+# download video talk if we need it (thumbnails are requested) and haven't yet
+ytdl_video_outfile="$yttranscript_cache_folder/rawvideo_$yturl_clean.%(ext)s"
+rawvideo=$(find "$yttranscript_cache_folder" -name "rawvideo_$yturl_clean*")
+if [ -n "$thumbs" ] && [ -z "$rawvideo" ]; then
+    printf "\033[32mdownloading talk video\033[0m\n"
+    if ! yt-dlp -f bv "$1" \
+        "${ytdlpquiet[@]}" \
+        -o "$ytdl_video_outfile"; then
+        printf "\033[31mfailed running yt-dlp\033[0m\n"
+        exit 1
+    fi
+fi
+rawvideo=$(find "$yttranscript_cache_folder" -name "rawvideo_$yturl_clean*")
+
+
+# convert into 16-bit wav file if we haven't yet
+wavfile="$yttranscript_cache_folder/audio_$yturl_clean.wav"
+if [ ! -f "$wavfile" ]; then
     printf "\033[32mconverting to wav\033[0m\n"
     if ! ffmpeg -y "${ffmpegquiet[@]}" \
         -i "${rawaudio}" \
         -ar 16000 -ac 1 -c:a pcm_s16le \
-        "$wav_transcript"; then
+        "$wavfile"; then
         printf "\033[31mfailed running ffmpeg\033[0m\n"
         exit 1
     fi
 fi
 
-# 3. Convert it into a text file
-# mlx_whisper saves the input file into an output dir with the same filename
-# but with .txt instead of .wav. I wish it had an option to specify file output
-# name but it does not
-transcript="$yttranscript_cache_folder/audio_$yturl_clean.txt"
-if [ ! -f "$transcript" ]; then
-    printf "\033[32mtranscribing\033[0m\n"
-    if ! mlx_whisper --model 'mlx-community/distil-whisper-large-v3' \
-             -f txt \
-             -o "$yttranscript_cache_folder" \
-             --verbose False \
-             "$wav_transcript"; then
-        printf "\033[31mfailed running whisper.cpp\033[0m\n"
-        exit 1
-    fi
-    # if ! whisper-cpp -np -otxt \
-    #     -m ~/.local/share/blisper/ggml-distil-large-v3.bin ./input.wav \
-    #     -of "$transcriptArg"; then
-    #     printf "\033[31mfailed running whisper.cpp\033[0m\n"
-    #     exit 1
-    # fi
-fi
-
-# 4. Create an HTML file to display, and open it
+# Create an HTML file to display. We'll add the text of the talk in the next
+# branch
 transcript_html="$yttranscript_cache_folder/$yturl_clean.html"
-cat <<"EOF">"$transcript_html"
+cat <<EOF >"$transcript_html"
 <html><head><style>
 body {
   font-family: Georgia, "Book Antiqua", serif;
@@ -146,9 +147,85 @@ p {
   overflow-wrap: break-word;
   hyphens: auto;
 }
-</style></head><body><p>
+</style></head><body><p>transcript of <a href="$1">$1</a><p>
 EOF
-sed -E 's/([.?])$/\1<p>/' "$transcript" >> "$transcript_html"
+
+# if no thumbs are requested, convert it into a text file and make an HTML page
+if [ -z "$thumbs" ]; then
+    # Convert it into a text file
+    # mlx_whisper saves the input file into an output dir with the same filename
+    # but with .txt instead of .wav. I wish it had an option to specify file output
+    # name but it does not
+    transcript="$yttranscript_cache_folder/audio_$yturl_clean.txt"
+    if [ ! -f "$transcript" ]; then
+        printf "\033[32mtranscribing\033[0m\n"
+        if ! mlx_whisper --model 'mlx-community/distil-whisper-large-v3' \
+                 -f txt \
+                 -o "$yttranscript_cache_folder" \
+                 --verbose False \
+                 "$wavfile"; then
+            printf "\033[31mfailed running whisper.cpp\033[0m\n"
+            exit 1
+        fi
+        # if ! whisper-cpp -np -otxt \
+        #     -m ~/.local/share/blisper/ggml-distil-large-v3.bin ./input.wav \
+        #     -of "$transcriptArg"; then
+        #     printf "\033[31mfailed running whisper.cpp\033[0m\n"
+        #     exit 1
+        # fi
+    fi
+    sed -E 's/([.?])$/\1<p>/' "$transcript" >> "$transcript_html"
+else
+
+    # Get the duration of the audio file using ffprobe
+    duration=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "$wavfile")
+
+    # Convert duration to seconds
+    duration_sec=$(printf "%.0f" "$duration")
+
+    # Loop through the duration in 30-second intervals and build a string for
+    # the clip-timestamps option of mlx_whisper
+    intervals="0,$thumbinterval"
+    for ((i=0; i+thumbinterval<="$duration_sec"; i+=thumbinterval)); do
+        intervals="$intervals,$i,$((i+thumbinterval))"
+    done
+
+    # transcribe the video into json format, clipping at 30-second intervals
+    transcript="$yttranscript_cache_folder/audio_$yturl_clean.json"
+    if [ ! -f "$transcript" ]; then
+        printf "\033[32mtranscribing\033[0m\n"
+        if ! mlx_whisper --model 'mlx-community/distil-whisper-large-v3' \
+                 -f json \
+                 -o "$yttranscript_cache_folder" \
+                 --verbose False \
+                 --clip-timestamps "${intervals[@]}" \
+                 "$wavfile"; then
+            printf "\033[31mfailed running whisper.cpp\032[0m\n"
+            exit 1
+        fi
+    fi
+
+    # Now loop through the intervals and output the HTML accordingly
+    for ((i=0; i<="$duration_sec"; i+=thumbinterval)); do
+        img="$yttranscript_cache_folder/thumb_${yturl_clean}_$i.jpg"
+        # I tried to find a video filter here that would avoid the initial
+        # black frame I'm seeing, but was unsuccessful
+        #-vf "select='eq(n,0)+eq(pict_type,PICT_TYPE_I)+gt(scene,0.3)',scale=320:240,unsharp" \
+        #-vf "select='gt(scene,0.3)',scale=320:240,unsharp" \
+        #-vf "select='eq(pict_type,PICT_TYPE_I)',scale=320:240,unsharp" \
+        #
+        # instaed I'm just pulling the frame from 1 second into the segment
+        # instead of zero, which is a pretty lame thing to do
+        ffmpeg -ss "$((i+1))" -i "$rawvideo" \
+            -vf "select='eq(n,0)+eq(pict_type,PICT_TYPE_I)+gt(scene,0.3)',scale=320:240,unsharp" \
+            -vframes 1 -q:v 2 "$img" -y &> /dev/null
+        printf '<img src="%s"><p>' "$img" >> "$transcript_html"
+        segment=$(cat "$transcript" |
+            jq -r $"[.segments[] | select(.start >= $i and .start < $((i+thumbinterval))).text] | join(\"<p>\n\")")
+        printf "%s<p>\n" "$segment" >> "$transcript_html"
+    done
+fi
+
 printf '</body>' >> "$transcript_html"
 
 open "$transcript_html"
